import cv2
o = cv2.imread(r"G:\test\images\lena.jpg", cv2.IMREAD_GRAYSCALE)
r1 = cv2.pyrDown(o)
r2 = cv2.pyrDown(r1)
r3 = cv2.pyrDown(r2)
cv2.imshow("original", o)
cv2.imshow("PyrDown1", r1)
cv2.imshow("PyrDown2", r2)
cv2.imshow("PyrDown3", r3)
cv2.waitKey()
cv2.destroyAllWindows()
